[package]
name = "up-rs"
version = "0.3.1"
authors = ["Gibson Fahnestock <gibfahn@gmail.com>"]
edition = '2018'
license = "MIT OR Apache-2.0"
description = """
up-rs is a tool to help you keep your machine up to date.
"""
documentation = "https://github.com/gibfahn/up-rs"
homepage = "https://github.com/gibfahn/up-rs"
repository = "https://github.com/gibfahn/up-rs"
readme = "README.md"
keywords = ["cli", "tool"]
categories = ["command-line-utilities", "config"]
exclude = ["tests/"]

[[bin]]
name = "up"
path = "src/main.rs"

[dependencies]
walkdir = "2.3.1"
shellexpand = "2.0.0"
structopt = "0.3.12"
serde = "1.0.105"
serde_derive = "1.0.105"
envy = "0.4.1"
toml = "0.5.6"
serde_json = "1.0.48"
serde_yaml = "0.8.11"
log = "0.4.8"
anyhow = "1.0.27"
thiserror = "1.0.12"
chrono = "0.4.11"
git2 = { version = "0.13.0", features = ["vendored-openssl"] }
dirs = "2.0.2"
slog = "2.5.2"
slog-stdlog = "4.0.0"
slog-term = "2.5.0"
slog-scope = "4.3.0"
slog-async = "2.5.0"
displaydoc = "0.1.5"

[dev-dependencies]
# testutils = { path = "./testutils" }
ignore = "0.4.12"

[features]
CI = [] # Enabled when running in CI.

# cargo-raze config: https://github.com/google/cargo-raze
[raze]
# Don't vendor deps.
genmode = "Remote"
# The WORKSPACE relative path to the Cargo.toml working directory.
workspace_path = "//"
