[package]
name = "up-rs"
version = "0.3.0"
authors = ["Gibson Fahnestock <gibfahn@gmail.com>"]
edition = '2018'
license = "MIT OR Apache-2.0"
description = """
up-rs is a tool to help you keep your machine up to date.
"""
documentation = "https://github.com/gibfahn/up-rs"
homepage = "https://github.com/gibfahn/up-rs"
repository = "https://github.com/gibfahn/up-rs"
readme = "README.md"
keywords = []
categories = ["command-line-utilities"]
exclude = ["tests/"]

[[bin]]
name = "up"
path = "src/main.rs"

[dependencies]
walkdir = "2.3.1"
shellexpand = "2.0.0"
structopt = "0.3.11"
serde = "1.0.104"
serde_derive = "1.0.104"
envy = "0.4.1"
toml = "0.5.6"
serde_json = "1.0.48"
serde_yaml = "0.8.11"
log = "0.4.8"
anyhow = "1.0.26"
thiserror = "1.0.11"
env_logger = "0.7.1"
chrono = "0.4.10"
git2 = { version = "0.12.0", features = ["vendored-openssl"]}
dirs = "2.0.2"

[dev-dependencies]
testutils = { path = "testutils" }
ignore = "0.4.11"

[features]
CI = [] # Enabled when running in CI.
