[package]
name = "up-rs"
version = "0.6.0"
authors = ["Gibson Fahnestock <gibfahn@gmail.com>"]
edition = '2018'
license = "MIT OR Apache-2.0"
description = """
up-rs is a tool to help you keep your machine up to date.
"""
documentation = "https://github.com/gibfahn/up-rs"
homepage = "https://github.com/gibfahn/up-rs"
repository = "https://github.com/gibfahn/up-rs"
readme = "README.md"
keywords = ["cli", "tool"]
categories = ["command-line-utilities", "config"]
exclude = ["tests/"]

[[bin]]
name = "up"
path = "src/main.rs"

[dependencies]
walkdir = "2.3.1"
shellexpand = "2.0.0"
structopt = "0.3.20"
serde = "1.0.117"
serde_derive = "1.0.117"
envy = "0.4.1"
toml = "0.5.7"
serde_json = "1.0.59"
serde_yaml = "0.8.13"
log = "0.4.11"
anyhow = "1.0.33"
thiserror = "1.0.21"
chrono = "0.4.19"
git2 = { version = "0.13.12", features = ["vendored-openssl"] }
dirs = "3.0.1"
slog = "2.5.2"
slog-stdlog = "4.0.0"
slog-term = "2.6.0"
slog-scope = "4.3.0"
slog-async = "2.5.0"
displaydoc = "0.1.7"
itertools = "0.9.0"
url = "2.1.1"
rayon = "1.5.0"
reqwest = { version = "0.10.8", features = ["blocking"] }
semver = "0.11.0"
ring = "0.16.19"

[dev-dependencies]
testutils = { path = "./testutils" }
ignore = "0.4.16"

[features]
CI = [] # Enabled when running in CI.
