[package]
name = "up-rs"
version = "0.2.0"
authors = ["Gibson Fahnestock <gibfahn@gmail.com>"]
edition = '2018'

[[bin]]
name = "up"
path = "src/main.rs"

[dependencies]
walkdir = "2.3.1"
shellexpand = "2.0.0"
structopt = "0.3.9"
serde = "1.0.104"
serde_derive = "1.0.104"
envy = "0.4.1"
toml = "0.5.6"
serde_json = "1.0.48"
serde_yaml = "0.8.11"
log = "0.4.8"
anyhow = "1.0.26"
thiserror = "1.0.11"
env_logger = "0.7.1"
chrono = "0.4.10"

[dev-dependencies]
testutils = { path = "testutils" }
ignore = "0.4.11"
