cargo-features = ["edition"]

[package]
name = "dot"
version = "0.1.0"
authors = ["Gibson Fahnestock <gibfahn@gmail.com>"]
edition = '2018'

[dependencies]
walkdir = "2.1.4"
quicli = "0.3.0"
shellexpand = "1.0.0"
failure = "0.1.1"
# Not a direct dependency, needed by Rust 2018 edition for some reason.
structopt = "0.2.10"
serde = "1.0.70"
serde_derive = "1.0.70"
envy = "0.3.2"
toml = "0.4.6"
serde_json = "1.0.24"
serde_yaml = "0.7.5"

[dev-dependencies]
whoami = "0.2.2"

