# See https://github.com/rust-lang/rustfmt/issues/2979#issuecomment-446227495
# Order: std::, external crates, crate::, mod.
merge_imports = true

# Wrap comments too.
wrap_comments = true

# Types before functions in trait impls.
reorder_impl_items = true

# Use `MyStruct {a, b, c}` where possible not `MyStruct {a: a, b: b, c: c}`.
use_field_init_shorthand = true

# Error on TODOs (use FIXME for long-running things).
# report_todo = "Always"
